# Generated by Django 3.1.5 on 2021-01-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reem', '0002_incident_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='diagnosis',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
